// <auto-generated />
namespace OnlineExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170306_6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170306_6));
        
        string IMigrationMetadata.Id
        {
            get { return "201703061230344_20170306_6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
